# Generated by Django 4.1 on 2022-08-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='rank',
            field=models.CharField(default='3', max_length=1),
        ),
    ]
