# Generated by Django 4.1 on 2022-08-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_item_stock_alter_users_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='Niet ingevuld', max_length=255),
        ),
    ]
