# Generated by Django 4.1 on 2022-08-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_remove_users_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
