# Generated by Django 4.1 on 2022-08-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='./page/static/images'),
        ),
    ]
