# Generated by Django 4.1 on 2022-08-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
