# Generated by Django 4.1 on 2022-08-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default='0'),
        ),
    ]
