# Generated by Django 4.1 on 2022-08-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_alter_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
